{{- $vaultca := genCA "vault-ca" 365 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-ca
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  tls.crt: {{ $vaultca.Cert | b64enc }}
  tls.key: {{ $vaultca.Key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-server-tls
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  {{- $altNames := list (printf "%s" .Release.Namespace) (printf "vault-cluster.%s" .Release.Namespace) (printf "vault-cluster.%s.svc" .Release.Namespace) (printf "vault-cluster.%s.svc.cluster.local" .Release.Namespace) -}}
    {{- $vaultserver := genSignedCert "vault-cluster" (list "127.0.0.1") $altNames 365 $vaultca }}
    ca.crt: {{ $vaultca.Cert | b64enc }}
    tls.crt: {{ $vaultserver.Cert | b64enc }}
    tls.key: {{ $vaultserver.Key | b64enc }}
